version: '3.4'
services:

  jaeger:
    image: jaegertracing/all-in-one:1.18
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: some-rabbit
    ports:
      - 5672:5672
      - 8080:15672
  postgresql:
    container_name: some-postgresql
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dcommerce
      POSTGRES_DB: dcommerce
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql